//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class IncidentDetail
    {
        public int ID { get; set; }
        public Nullable<int> ApplicationID { get; set; }
        public Nullable<int> IncidentID { get; set; }
        public string Description { get; set; }
        public Nullable<int> Severity { get; set; }
        public Nullable<int> Priority { get; set; }
        public string Status { get; set; }
        public string IncidentCreateDate { get; set; }
        public string IncidentAnalysisStartDate { get; set; }
        public string IncidentClosedOn { get; set; }
    
        public virtual SupportApplication SupportApplication { get; set; }
    }
}
