//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace IncidentManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SupportApplication
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SupportApplication()
        {
            this.IncidentDetails = new HashSet<IncidentDetail>();
        }
    
        public int ID { get; set; }
        public string ApplicationName { get; set; }
        public string Description { get; set; }
        public string OperatingSystem { get; set; }
        public string LastUpdate { get; set; }
        public string ModifiedDate { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<IncidentDetail> IncidentDetails { get; set; }
    }
}
